---
title: "Preparing the caloric restriction 2020 dataset for ExperimentHub"
author: "Tram Nguyen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 100)
```

## Data pre-processing

# Make `SingleCellExperiment` data with all tissues combined

```{r}
# Load in all samples
file_list <- list.files(mydir, full.names = TRUE)

# Filter files containing the pattern "all_rawcounts"
tissue <- "all_rawcounts"
tissue_file <- subset(file_list, grepl(tissue, file_list))


# Get sample names from files
mytitles <- basename(tissue_file) # get just the file's name
names <- sub("_all_rawcounts.[a-z]*.[a-z]*.gz", "", mytitles) # Grab only Sample name and tissue
names

# Read in the filtered files
tissue_data <- lapply(tissue_file, read.delim, as.is=T, sep="\t", header=T)
names(tissue_data) <- names # assign sample names

# Merge data frames in the list based on the common column 'ID'
combined_df <- Reduce(function(x, y) merge(x, y, by = "Geneid", all = TRUE), tissue_data)

# Extract row names and remove them from the data frame
rownames(combined_df) <- combined_df[,1]
combined_df <- combined_df[,-1]
colnames(combined_df) <- names

# Convert the data frame to a sparse matrix
mat <- as.matrix(combined_df)

sparsematrix <- as(mat, "sparseMatrix") 
sparsematrix


# Print the combined data frame
head(sparsematrix)

c.sce <- SingleCellExperiment(
    assays = list(counts = sparsematrix),
    colData = DataFrame(sample_name = colnames(sparsematrix), tissue_type = rep('All', ncol(sparsematrix)))
  )
rowData(c.sce)$gene_names <- rownames(sparsematrix)
rownames(colData(c.sce)) <- NULL
rownames(c.sce) <- NULL

colData(c.sce)
rowData(c.sce)


# Save RDS object
#saveRDS(c.sce, "../caloric2020_sce.rds")

```

# Read the raw counts, gene names, and barcodes for each individual and tissue:

```{r}
suppressPackageStartupMessages({
  library(Matrix)
  library(SingleCellExperiment)
  library(DropletUtils)
  library(readr)
  library(dplyr)
})

mydir="~/Documents/Rubin Mouse Aging/data/caloric 2019/GSE137869_RAW"


## Work through each tissue
for (t in 1:9){
  tissues <- c("Muscle", "Brain", "WAT", "Skin", "Liver", "Kidney", "BM", "BAT", "Aorta")
  print(tissues[t])
}

# Load matrix
brain_matrix <- loadFiles("matrix", "Brain", mydir)
muscle_matrix <- loadFiles("matrix", "Muscle", mydir)
skin_matrix <- loadFiles("matrix", "Skin", mydir)

# Read gene names
brain_genes <- loadFiles("genes", "Brain", mydir)
muscle_genes <- loadFiles("genes", "Muscle", mydir)
skin_genes <- loadFiles("genes", "Skin", mydir)

# Read barcodes
brain_barcodes <- loadFiles("barcodes", "Brain", mydir)
muscle_barcodes <- loadFiles("barcodes", "Muscle", mydir)
skin_barcodes <- loadFiles("barcodes", "Skin", mydir)


# Create SingleCellExperiment object for each individual and tissue

#create empty list with length of zero
brain_sce_list <- list()

#create empty list of length 6
brain_sce_list <- vector(mode='list', length=6)
names(brain_sce_list) <- names(brain_genes)

for (i in 1:length(brain_barcodes)){
  
  cdf <- makeSCE(matrix = brain_matrix[[i]], genes = brain_genes[[i]], barcodes = brain_barcodes[[i]], tissue = "Brain")
  
  brain_sce_list[[i]] <- cdf
  
}

# Print the results
print(brain_sce_list)

one <- brain_sce_list[[1]]



for (i in 1:3){
  
  type <- c("barcodes", "genes", "matrix")
  type <- type[i]
    
  # Get a list of files in the directory
  file_list <- list.files(mydir, full.names = TRUE)
  
  # Filter files containing the word "Muscle" and ending with ".mtx.gz"
  tissue <- tissues[t]
  tissue_file <- subset(file_list, grepl(tissue, file_list) & grepl(type, file_list))
  tissue_file
  
  # Get sample names from files
  mytitles <- basename(tissue_file) # get just the file's name
  names <- sub("_[a-z]*.tsv.gz", "", mytitles) # Grab only Sample name and tissue
  names
  
  # Read in the filtered files
  tissue_data <- lapply(tissue_file, read.delim, as.is=T, sep="\t", header=F)
  names(tissue_data) <- names # assign sample names
  
  
}




brain_files <- subset(file_list, grepl("Brain", file_list) & grepl("*genes*", file_list))
brain_files

```

## References

Ma et al. (2020). Caloric Restriction Reprograms the Single-Cell Transcriptional Landscape of Rattus Norvegicus Aging. *Cell*. 2020 Mar 5;180(5):984-1001.e22. doi: [10.1016/j.cell.2020.02.008](https://pubmed.ncbi.nlm.nih.gov/32109414/). Epub 2020 Feb 27. PMID: 32109414.

## Session info

```{r}
sessionInfo()
```
